DROP DATABASE IF EXISTS `georisk`;
CREATE DATABASE `georisk`;

USE `georisk`;

CREATE TABLE userpref (
	`id` INT AUTO_INCREMENT NOT NULL,
	`city_name` VARCHAR(100) NOT NULL,
	`rating` BOOLEAN DEFAULT 0,
	`review` VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);